# Generated by Django 6.0.7 on 2026-07-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.IntegerField(null=True)),
                ('emp_name', models.CharField(max_length=100, null=True)),
                ('emp_balance', models.IntegerField(null=True)),
                ('emp_hour_no', models.IntegerField(null=True)),
                ('emp_date', models.DateField(null=True)),
            ],
        ),
    ]
