# Generated by Django 5.0 on 2026-08-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_off_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_info',
            name='emp_date_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emp_info',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
