# Generated by Django 5.0 on 2026-08-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_off_app', '0002_emp_info_emp_date_update_alter_emp_info_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_info',
            old_name='emp_date',
            new_name='emp_date_created',
        ),
    ]
